version: "3"
services:
  tensorflow:
    build: .
    runtime: nvidia
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./config:/config
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
